auth:
  existingSecret: mariadb-secrets   # name of the secret
  existingSecretPasswordKey: nextcloud-password   # key in the secret for the user password
  existingSecretRootPasswordKey: root-password   # key in the secret for root
  username: nextcloud
  database: nextcloud


primary:
  persistence:
    enabled: true
    size: 20Gi                   # adjust based on needs
    storageClass: longhorn       # your SC for persistence

service:
  type: LoadBalancer
  port: 3306
  nodePort: null
  loadBalancerIP: 10.0.1.159     
