
auth:
  existingSecret: mariadb-secrets
  existingSecretRootPasswordKey: mariadb-root-password # The key that's failing
  existingSecretPasswordKey: nextcloud-password       # A key for the Nextcloud user
  username: nextcloud
  database: nextcloud

primary:
  persistence:
    enabled: true
    size: 20Gi                   # adjust based on needs
    storageClass: longhorn       # your SC for persistence

service:
  type: LoadBalancer
  port: 3306
  nodePort: null
  loadBalancerIP: 10.0.1.159     
