---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: storage
spec:
  encryptedData:
    rootPassword: AgAg2XBNkwhU/CqBG/ILXdm7Gv/P5geudP4kFVshROysRhZjMNyerCNqro4JaCGvyViFINbLd4nc0m5yVj/Wb+KJBwG+9J3spsAvTw1ywrFksJcphd89j5Pk6wsXza/C2BqQjDghd9kguMyRX9n/3vKYzRpzYu0rOObAVxeqFtTa31DM/P/5Zyngg5cm4yf0OUKj/GwtoX7CYEbb1dblnorcZds5usCkR5a2Yv77Jah/pnZLsWnxrFEGW3bdZreUzciJa5MXUHdw9rjs+4e2qosatsYFLThMwCw+hFRpwOEZSW4DcKdCNaycSqSDMZEVUpxbyyJeR19U+6IVEkOX/784W08mVSskrzATAuPpG2rODZHw3XGgsfXIMKHqbMymDmOBNS6BaRJKInFsiuTA/DvxhLf3e7XTHa2uytxy71boivgFfyRgHAEU/x5DmFh6UfUqok5SSjctKRr/KjR6mQh9rc+eCQuF43thrBgn8yPi1yZEvyQhpebn+ufchAJ3ExM/wEtqPdRn44z55Nb09FIL7P//gSf4+LOS2j/NcoIhK3fyR7Tb0+XKDN0zU4YnuNXZsejviF/e69TwnJydHSc3k+OqCW6FrVRa5VM5FLLoC9ngPx1yH/68Vc2m5RD9auqNt58vfJj7DEqM86LN+kDCAZgU/A7yULyIMNJQ7Sw90BrRbB2wFjUwwz3nrBaKOKtqz3vjU/R028+5AhsJ4WY=
    rootUser: AgC/dqqMT3j2dunKLVZg7nM3h8TTO3u0S/04ZZkHoq0UOxjiA2yOOc9diNba+uB2QmlcKpj1Svn6igL7R/Wxotd3ZyTn2Dg+7UKv1qLlnxJcp5m/Bjr9uRYtzmyWEBwQwNmXpeH4LH68INQjrHuCYEDWZHvSOhKOntFGcInoJl9AWmV2C0oNwMP7oi5ATqx0F5LvXmALOVi8s5/iWBJzLGDCKq4wQr7PVGTgbym05QuyCyrCkgDfE0P6vWh7zM9ri62tKQMfNYWojzmQJ16juB+HT6zoGV4D16D4ln/YybP12xYunT/3fXBcTLegfu+SoO4MTAbOySUUGrAxCBlALYEQP4JbJWnnQbvUmdeeUTMvZ+OE7iRus/QfyZBtnsaUXLBs6bCZSLHTgb10DjczI/toulnEPqXvmkqiDEpLltyEalmINf8j5S1CV2/TBZu0csxSiL4i92wXPp0RwXSCET76lrcvs0v/sV+27ni5U5VYNFG3a+8P3ELhKLOTT9LmaNTjYjLPdTn+qTfBGcMFBFePRS2NFYt8EH5fs9/Jj1WsKOgbsun7CJi4HF7yhCyZeYG3li+jgJcx1ae8Q8wnrf8vVc/ExP4/FA8fWYeYb8FNGz16WGOgXh+0TdfMr1JFIFjrONs1OTWIDYZbodBhG779UlM90Kk6R25xvvHWKM7uUskXZ1f7HB7YVETc5YPZv5CozboAVw==
  template:
    metadata:
      name: minio-creds
      namespace: storage
