---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: storage
spec:
  encryptedData:
    root-password: AgAHQv9ehlfhUT45bdJ19CjIVO4+JtgvJVcp8yNCUaGKok4/FqYe0aSzUnk+O7+V8WqXwZd7NVJD8II/xJEuCMYdyHRLrekrgCboHVCoVWAYoaSiMyn11dOOTd4UFreWabqdLwpiHk3wjFPbysqnXkMsk+UitukdnMCjQJqe4jDMuUoXglblojgCHHUgrKcDgVjuPTqESpvinSp/i2ClWalMQbyd5qUUuEVDbcGk180rJdsdeFdOjFzHOf7oAO1HDsdE98KtxL4rL/uo6JWDItO7JSLYMFA26gHnzUGtozlGwGeGB0nz4/BK8iFjo+y4rBTUA/PQyzJ0CbEEMSOvj5xREfjbTD6OwL4+gSVdJRXBrjmzeevBq+SszPoI5OGKF6nKBzxuItQLLiTGBEJgn+/G3ZzQ6iAp/YFUIljjaZCO+uhF+b7368epwMWALJIXGAxm5FsJnaQpfrOd7mobesl028mfip9wWolO0hUY47rcLrLAY8KejOtEimqvZ+8aU4YoTdLfKqHisE0qbgqylhYwHJh2isZRoFEwVLk2U98ac286JAouTy+AZnFU/RyUNC/0oQaK60J07paxkfvKlc2o7D+ozeN0gJ7fVhsSlzZBlft6wsZL2rl/xqja7BTrQ60Kk4PE/jRzqMYlTtFtGCdDXzarDZl32YksHSgDyOyg0ChttHiQOgtvTXZfFBlT29AeK2NZCl/hUEk4tHbO6g==
    root-user: AgAhMprFWuVPU8HTtVaTfHTao/e+GL3wsL5jhz3ZZhaiNMcM4Lrr3tnkaMP6Vfdg5nETIVXtTUC4oMhGzpFLoU+pPqPRjiRWJvXRK+hboM9KARsr+/6+Ui0gkKkiijo4utnGbwrYC3mb5j+S8e6dgmdzs8/g2u9rkQSRGLhHzFm51+OvLKSNXRVkCv1ShtqQqWx/+FTUlZSeFLSuDxqlzIXV99d3Sraq2/SwAoZd7QnwAkjPDReIUno44R2RhIfae3jP79r9efRCQYCTvZT7wKKIw4hd4MAn1PMaLHJ6i1IbvPA8J9Jhuu+Y3DDVR8xoGkVV+TJEBycfl0YH09Mm7AlcpQOcTnlg/cYfqfpZfj6kYMx+jvP8JSrFpmk8OP3yTm6EdKwKNsaZudU6dzoTWCgbbSAgbBon1/c+bE/c2OfZWzGHMpYk8vupJUGpMWgXdwFgJcoX+eqvi0wX8S1XfeLeEfM1mf+sAXLk6t55bG6qjZ5cnF9RgZ9+TMswLrRpLFrMj30sOX8GYD+AKMfCCErEjxyDOLTjYTpGF7IUjS/ak3CgYKOIPjDdYLwMWJOP+OAzV0HUEMvD1VncYSufs6rn2HKa8Hm7aIuQURX6VKLVIRYBFgIJedhA6YovHoNaaho40LnUf+G0JvjWXR0XG24eTOF4jvK2vMGTiIb2liymXhBJpjudu4CzeqDpRqOYI54A6mxmuA==
  template:
    metadata:
      name: minio-creds
      namespace: storage
