apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: AdGuard Home Helm Chart (OCI)
    - repoURL: ghcr.io/gabe565/charts
      chart: adguard-home
      targetRevision: 0.3.25
      helm:
        valueFiles:
          - $values/charts/adguard-home/values.yaml

    # Source 2: Your values repo
    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: adguard

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
