apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # This points to the parent chart within our own Git repository
    repoURL: https://github.com/jadogg22/homelab.git # This should match the repoURL in the root-app.yaml
    path: charts/arr-stack-parent
    targetRevision: HEAD
    helm:
      # We can override the parent chart's values here if needed.
      # For now, we'll use the defaults committed in the values.yaml file.
      passCredentials: false

  destination:
    # This field is ignored for parent apps that create other apps,
    # as the destination is specified in the child apps.
    # But it's required by the Application spec.
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
