apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: The official Helm Chart
    - repoURL: https://democratic-csi.github.io/charts/
      chart: democratic-csi
      targetRevision: 0.15.1
      helm:
        valueFiles:
          - $values/infrastructure/external-storage/values.yaml
    # Source 2: Your Git Repo (where the values live)
    - repoURL: https://github.com/jadogg22/homelab.git 
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
