apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emulatorjs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: oci.trueforge.org/truecharts
      chart: emulatorjs
      helm:
        valueFiles:
          - $values/charts/emulatorjs/values.yaml

    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: games

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
