apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Multi-Source: Combines the chart from the public repo with your config from Git
  sources:
    # Source 1: The official chart
    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 2.1.0  
      helm:
        valueFiles:
          - $values/charts/homepage/values.yaml # Reference to the secondary source below

     #my repo
    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: main
      ref: values # Reference name used in Source 1

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
