apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  
  sources:
    # Source 1: The Official Helm Chart
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: 5.0.x
      helm:
        valueFiles:
          - $values/infrastructure/minio/values.yaml # Uses File 2

    # Source 2: Your Git Repo
    # This applies File 1 (StorageClass) and File 3 (Sealed Secret)
    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: main
      ref: values 
      path: infrastructure/minio 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
