apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    # Source 1: The Official Community Chart 
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 81.0.0
      helm:
        valueFiles:
          - $values/charts/monitoring/values.yaml 

    # Source 2: Your Git Repo 
    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: HEAD
      ref: values 

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 
