apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bjw-s.github.io/helm-charts
      chart: app-template
      targetRevision: 3.2.1
      helm:
        valueFiles:
          - $values/charts/radarr/values.yaml

    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
