apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: romm-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mariadb
      targetRevision: 24.0.1
      helm:
        valueFiles:
          - $values/charts/romm-db/values.yaml

    - repoURL: https://github.com/jadogg22/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
