---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secrets
  namespace: default
spec:
  encryptedData:
    mariadb-root-password: AgDArfuOX/JkoaXp+ssJBAGV7ZUN7D+e6otCX/F7UjMMzbhx4YoXJQGBgeUCjnbccNZJSedBuCvCSDdKSRCqWkAWo8jp2ZlE0Cw2BSqq2UEIA4OBiDL6E6Z9b+secpDbQpnfUjq1VqORJ2PDnOxhq9aykO4iEAtJlTQxpfwHS2Z+WpNYQy71pNoHHaPVDrjpXEQ4+YB3/2YXrS88TuBGQtDoR4MQ6g/vAMcrG73pp1SqTbP9hehpsrrp+UfbRJ9nmSEE+B3uoJRKxK1wkjUxow5P+QPK8jPYE4qU3Kug7vqb3CMnA/d6tE6cHeOBKTv1/hbhJ4WGnXAV2EBA08WTXZkLnq27izs246op8vCSkWm1DDDKiXHB/IDRGx2GlqxIrLYL1TXiFBOrvgaVebJDmkxjJXkxQG/1LQEn2XDH67VnozicPlu5Uy3APZBm6GzY/xG9C539UAk5V7dqU+ZqB6oFPMalhPncwv6U2X3hGOs+KJ432Gkg4sn7ldf0TV+DPQn30OJ4XBSQ0Auh6XNBo4Go/uRQ0H3HlBYOtCclRb43p7mtBZT+W0TY2whcwIEl44+GJY2UuygP9o0zKbssTj4cA52tzl6a5CqakJbtpeVDebita8hGamv7lCG5IWmRqGTKgV9u+Hq1EYhBOay1J+Jx+XtfutzEU0/X72z1/dE6NtEdogqaMJ/bt49geL9M+ScFn4DlrcaeovN2LV6dsQ==
    nextcloud-password: AgBhw9EQYRezBTb+UmiUkzA9U1ts3hEy2MAEeQPZreXvD5wdRNnuT5kyXx2Hf/m7yWQFxYFXBmemgzHEj3KjF4J7XEIaKkSaFhmR+6v23mPc432lLvYf31S7Qn9UGSMQGXZKy/+tuZypVpLOHF194JbI5saTHaaBXHx8q0GQnE5gwcJtZ59v6mSPkvFW/SRAH/T4/OY6AlWTf7Ucoi4rVrROg07m3ZuaIrPpzYySYguT+qEyg0vyY5mQD8MTyjXtZhoDnKeUpVIDIE8r82FCzSfUO3nKVFLpey/g8bw7Ou79CXTFfJ1ADiMOMJuEZmCOf4aldNrtwgEP5nnPfQ8ZsKsn7+KvzwVB2WBwqcIA+TP4AnawLAwy1+WdHFMeeJWMjBPjBqJup51j9jk2VYc7/LCmOFD2dTF6jQBqq5NWM3WxCXe+08eYnA4iavj+hzgpD8LozW/5Oto27Ep1tQNL/ihlvcu+5kxX5l0Pii7XO5lExaYEM+vWju4r2b1HuoSvQY2k6YlFeREe8FZnjBqCY1pN8NxQupw1kAanpKna7iPozq6FjzRUnKXSqPXZdLGdZcSxpT6iatvhG3jm34BWH2f+ao5L0pzQPkJTi8jfSSPFTnS+SGaq/27IK1RhIIdmovA7MftWAelvNJwkv7ja9pIDsP/RBws7FLYkriGZ1Z9U0xwoFPGkpvYccf1WLTemE2XaYmzmTGdR1lXEk6o=
  template:
    metadata:
      name: mariadb-secrets
      namespace: default
