---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secrets
  namespace: default
spec:
  encryptedData:
    mariadb-root-password: AgAmMGd7qck13SkqWrWf7Qp7H6x3NnEPe4TkTuvytUgbGG7jT8D19ygrD+U+3w9b6vf69U6i3O1aXJR0NCNYgHh6bjUR01YweYlbB859hObWIBsB6Oeh/7hQXE/TA4+w8dnFwdSev9aMJr9BMQUKIqooaAQE1WYbetYwTcJuHXTfQ1e3mwfUftzHc7bltf4Wh8xsVjhbLRT17OmKWF2ptkxGGv4HgS+9WaWU2zK0+rUXFvsiz4NSguJDGCnWmJhEsqcaivJ4oxzglrTkuXT9fN8EzK9crp1W0yP10m717ue5dU+wEbwEXi5Lrgl564mka0JvmGJ3pnJme0qVPGz+vSpKGbTEpngpjXfih+/BQDum8WzbA3Yw0YexRy8T9yikswI2I2BnSPzYtvB68DRtFxEznFjfO/Mky+ye/RU6aJN6Tnst60q/H8T/EIyTDt5ec4lJ5zB2gjOMjpCAO/F8rtCMnfEjISiIHlJf078TYU0rxgvRUvBiVdfVD8IT1HZIxWd7bA0P41GmgsT5r7ZaUg78OJsTTc8odm1I82S8/KJrYKVbSgwAeY7ECkWRbaoY7gOyidEJg8Y/OyKP+eaxpbCGf1lyA+vl+U0fC+aGGRseVy+hnH1HlQV3TesdJEAG8JsF5LQ4O8MkPGHy244FZ7N6D8W9SNdVnUIpj1IDsDeGMaFbgBke0imUvohemCMstRLquXcOZ4jPHk6tQf55xw==
    nextcloud-password: AgC+ZhbQoN581H4niYXPHCUMgjA//jHZP9A9mo0K+dGhrneVnfuR6o0xlcFmNUPkjUmy7dPC8/QfkMZ9/PyNr6rE15CgqpoWQEZS7FeJdoUM+uzepV07GQJHNi8+7jtZJxhJikheNYbeDYdtCBEx1vV+QvSY35v0B69BCZVbcfEDmK//WDkA5nY64SmCkagT2cw35+uI8kS9PMFVLeka+58f0hvrN6nTwxJRZAKgUSX6XWf3qowM6YGVtQhliPECQysEx2TXug1WYpG9tSf6JjHCAhKgNyVIXo7XxwetrVzf2Cc4NyX9uKrPrXW71i4RFI7E98ma5KKYCuAhFPq8rM4lyLE+wJoxPWPS5W+I+KXjGPufFaThxAfRnAKFr3YWu00amPtKRR7mTNaYz/YAaOokEivq8CZ6FEZ3aCiGW3buE2BzXDd5LmsuFAuYxM2RrzBvpUDl0jD2uvESsItxhWwpHqFZKUtXYv1xv6R/u8vTfNpxrz+EKVkl44dbCdJafJEPT8ovZr9A1R6oh2queeJ9EPbuTddBZhJP4h+nxEXI1VRtbDHMAeEps1G7g/DEaOPY30Xdy9v0nhfmM8yUFBNDUD55JbONJCDn+gdqid576XwKUaEbXPVuwwi9VRSwxZujzzhnovilzllJiKg+OO4caKbJxm8xzNpdmoNXut8uqhTL4oQqZVPDVfX2VVc0XjNwyBZj5o3jtPdm2ik=
  template:
    metadata:
      name: mariadb-secrets
      namespace: default
