---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secrets
  namespace: default
spec:
  encryptedData:
    nextcloud-admin-password: AgA4Zh5dYIxgl+HU5Ax26dglBFjjwzTxJRTxaf4i11LJ8xgxoSGeeXLIHU9P1oIrn8m/j80Rc/O5uOaY6V4vkZ5erNIMocF9uzAfsY9mgECXNFKC/bZ4AZoAcSp1eRaQmdykHdji73CtCqTGTiYs4J4Ay53244QL5thHr7rOfiA6hw7hlWDAgNbpfJsf+gkW2oe+yUP8oWoQMZqDpkqzEqDkUXrBnA9ahaeuqVcj2oMu0+IsRHv1aWdQK+Jmn8cH/0JJhvnI8k6imZmMxff9L5sMMctZnbUsCq5AlI5pZKMCMeMswOHP+09rrnkqrPN3qfu6d87Fe5mfDofRsP0Ou89CMGT7b3gMhHoHbhzxbK+LyklD4HAtVQyJcNcXRFPmD3fSPQrfWLgLe34e23UMm52A4o6qsKi+B4EGJFKi/ufVsurL8O2HuruW2f9iSC1EwPHQH/sOrLrK3bZXOmRjtXwGszTFNJ2lsxPHPF8VyXQMcF8gHPo6DCM3HN3e7Ui91iVhGuTc5oN0+A+48JdtWtGBLtCs01xxEMvTPKycKQhDCNVKw2P9ypixUJGhIlatUl5iBkppqRoJ0GxCqgSdAR7/vcqyQYcZcpnHe7LirANhKQDBHClAdiIQraO1fwQu8UayzJC8P+pzsD0f5XubP8caOpDIIryX6S5GcubMQwqOs8cSNpwsL9zNmo6GCzZxlwEYvJZxpcumQjev
    nextcloud-username: AgBKBrHWJqrkeKgl2iiXlisrWKncftPnKQqQ7cip5XrQIbRXtakKO5g8BMWw4mrhxJLtgjgXdg0nHX/sgak2aabwbql05K2MPZuOa1DXpP7RCPK+ip6kB0F1ARYFooLhQQ3ojY7Q3NV3iwAE3MfVMso/XOoH35i7rEY/mXhpah8T2x0pCAiLSBAY/b94hPTToLFAZZ8mBhruT3LjsjPqyJqfTPAbV1ZEZ704Pk4QRYxljjhdcQH3kBzx1ni9l1LQJzcqgIAXO4E4XLUVE1zi8Fc4JhanuGnb34U83uktexzEIIUbm46xKyqaGzEPIQfvFftf7ujpH20gnlWnQU8vMLAtuzxD+1vQJ2aj1k87tdOxtDd13gnYwNUPP/Ag21BBWJTmox8bHc8uWdF+xcWNabALbDYEjBOAwfjgxY0Bch6a3v4x5IFmJrZ/6mFnO/q1V3K8a7cEYHXhmbcFWzIUTn0BnGwxq6kJRSNf+2Ex+Zw91QNb8EiCUKHZLg2qf4tZ1GwA5w/FqyN08UfGOFlU0XW5ENRI9Uubrz6lxRM9v+jYo6qjVXcM3QrON+uBpGIrcwdX52D1ksERcex+E5+3mcgcbByYRKJYmv2JNqI8dtqjEskpocvUXHBnq3cFr1XRk21t4yCv6Htsn2K5fYkUDVIdy/MDsK97IXheJhu5xBCC6Myrhg7OxMx5gqRWULLEg6nS+YrZwg==
  template:
    metadata:
      name: nextcloud-secrets
      namespace: default
