---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-secrets
  namespace: default
spec:
  encryptedData:
    nextcloud-admin-password: AgB1xYOQMONJmM/Z3a3yozuLtA7+ElZX23zEhAYOpwBBk200/Nl3zbZI0cRWsLXeAoD2KCpVhkSYYuLlcHetKs+qeVjp+Z6G9eKVBJGf8RMOKqcN9s3WZ+FLJlVkUHxxKKbMPi6znIi+AiTCKWkW7A2mlAKxtTU4UCUqm7Z1r7sxb7pbkSGSdiNLN6KONZp0sMs6OYxlffCVSt7WLWEWE5OQQ+V268BHItSMMaXABHZaOZ3R1IHbEc88HwVPcAAElzCFwTo+MzeBvVsmC4RRuBHnjRElXGqrvcQDwf8sSf2HA3QKQuLTVGV+ePDDvIvlg9wzuS3OCvIgN/1NAWUW4ojI4nMHxxjPHJNfi24v2YGPqtO05z53/LY8I+tJotwxMo31Wvo/gC80RVh3rjLmzn4Ci090ZE6pWDARgbSqcUpHG+dTeZckG6gzRC6alxGL5WDi/kT2jpynqUb9PWw66WjhXOqCk/GHATRJP9OStmg6nPtRH5wX6BYLkMovKOx7YbfZGBqJ1wHi/uk/a8EPndRi7XgG8jbJcPNtnmkejRuaGMH4S8lEUi+hLBdwxHrSThhTrSLWALvNhPrTiSVoav/qpS/D8G/KZ6CMbvruDu798eS2sVXMKZXY/2AQ+css0mtq7blgJzg9w5BkWc14O+nw4X/y8lc3pDFo2svca5FNRgJmAHKnVyiETRuHoQe0MV+To2CvzCkZNTSw
  template:
    metadata:
      name: nextcloud-secrets
      namespace: default
